apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dbi95zo1k-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/dbi95zo1k-dotnet-basic